name: Drupal Check with Reviewdog
author: Reload A/S <info@reload.dk>
description: Run Drupal Check and add results to your PR using Reviewdog
inputs:
  paths:
    description: Paths to run drupal-check on
    required: true
  check:
    description: Check `analysis` or `deprecations`
    required: true
  reporter:
    description: Reviewdog reporter
    required: false
    default: github-pr-check
  workdir:
    description: Change to workdir before running (if composer.json is not located in git root)
    required: false
    default: .
env:
  GITHUB_TOKEN: GitHub API token as provided by Github Actions
  REVIEWDOG_TOKEN: Reviewdog token (optional)
runs:
  using: 'docker'
  image: 'docker://reload/drupal-check-reviewdog-action:latest'
branding:
  icon: check-circle
  color: purple
