name: Drupal Check with Reviewdog
author: Reload A/S <info@reload.dk>
description: Run Drupal Check and add results to your PR using Reviewdog
inputs:
  paths:
    description: Paths to run drupal-check on
    required: true
  check:
    description: Check `analysis` or `deprecations`
    required: true
  reporter:
    description: Reviewdog reporter
    required: false
    default: github-pr-check
  report_name:
    description: Reviewdog report name (if unspecified uses `Analysis` or `Deprecations`)
    required: false
  workdir:
    description: Change to workdir before running (if composer.json is not located in git root)
    required: false
    default: .
runs:
  using: 'node12'
  main: 'main.js'
branding:
  icon: check-circle
  color: purple
