name: Build and publish
on: 
  push:
    branches:
    - master

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build the Docker container image
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/check:latest .

    - name: Push the image to GitHub Package Registry
      run: |
        docker login docker.pkg.github.com -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
        docker push docker.pkg.github.com/${{ github.repository }}/check:latest
